import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" data-oid="4lmtb8q">
      <body className="antialiased" data-oid="uahlg:9">
        {children}
      </body>
    </html>
  );
}
